apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lhw-openproject-prod

resources:
  - ../../base

labels:
  - pairs:
      environment: production

images:
  - name: docker.io/postgres
    newTag: "16"

patches:
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi
    target:
      kind: StatefulSet
      name: poc-postgres
  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
    target:
      kind: PersistentVolumeClaim
      name: poc-postgres-backup
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: poc-postgres
      spec:
        template:
          metadata:
            annotations:
              vault.hashicorp.com/agent-inject: "true"
              vault.hashicorp.com/role: "poc-role"
              vault.hashicorp.com/agent-inject-secret-db: "secret/data/poc/db"
              vault.hashicorp.com/agent-inject-template-db: |
                {{- with secret "secret/data/poc/db" -}}
                export POSTGRES_PASSWORD="{{ .Data.data.password }}"
                export POSTGRES_USER="{{ .Data.data.username }}"
                export POSTGRES_DB="poc_database"
                {{- end }}
          spec:
              containers:
                  - name: postgres
                    command: ["/bin/sh", "-c"]
                    args:
                      - |
                        # Wait for the file to exist, then use '.' instead of 'source'
                        if [ -f /vault/secrets/db ]; then
                          . /vault/secrets/db
                        fi
                        exec docker-entrypoint.sh postgres

    target:
      kind: StatefulSet
      name: poc-postgres
